spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:forum
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    #defer-datasource-initialization: true

  h2:
    console:
      enabled: true

jwt:
  secret: ?Qv/Ih=R=R?1s=$S80O=;E-DvEVx9,