spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:forum
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    #defer-datasource-initialization: true

  h2:
    console:
      enabled: true

  mail:
    host:
    port:
    username:
    password:
    properties:
      mail:
        transport:
          protocol:
        debug:
        smtp:
          auth:
          starttls:
            enable:

management:
  endpoints:
    web:
      exposure:
        include: health
jwt:
  secret: ?Qv/Ih=R=R?1s=$S80O=;E-DvEVx9,